server:
 port: 9898
 

 
 
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.Oracle10gDialect
       ddl-auto: update  
  datasource:
   driverClassName: oracle.jdbc.OracleDriver
   url: jdbc:oracle:thin:@172.28.224.1:1521:xe
   username: hiber
   password: pass
  application:
    name: Auth-service
  aop:
    proxy-target-class: true
 
logging:
  level:
    org:
      springframework:
        security: TRACE
    
    
jwts:
 secret: "asyudfusdf2323aSNDJAN982837278AJDHBADSBSJDSVSCVSDFVERS3432"



eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:5000/eureka
 