server:
 port: 9898
 

 
 
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.Oracle10gDialect
       ddl-auto: update
  datasource:
   driverClassName: oracle.jdbc.OracleDriver
   url: jdbc:oracle:thin:@172.28.224.1:1521:xe
   username: hiber
   password: pass
  application:
    name: Auth-service
  aop:
    proxy-target-class: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      group-id: Employee-creation-termination
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: '*'
#        spring.json.use.type.headers: false 
        spring.json.type.mapping: EmployeeStatusCreationTermination:com.microservice.authservice.DTO.EmployeeRegistrationStatusEventDTO

 
logging:
  level:
    org:
      springframework:
        security: TRACE
    
    
jwts:
 secret: "asyudfusdf2323aSNDJAN982837278AJDHBADSBSJDSVSCVSDFVERS3432"




eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://host.docker.internal:5000/eureka
 